targets:
  - name: "富邦員林"
  - name: "元大竹科"
  - name: "凱基台北"
  - name: "凱基松山"
  - name: "元大土城"
  - name: "元大永寧"
  - name: "統一台中"
  - name: "富邦嘉義"
  - name: "富邦虎尾"
  - name: "富邦建國"
  - name: "永豐金總公司"
  - name: "元富總公司"
  - name: "統一總公司"
  - name: "凱基總公司"
  - name: "富邦總公司"
    max_ratio: 0.6
  - name: "群益金鼎總公司"
  - name: "凱基城中"
  - name: "富邦南屯"
  - name: "元大士林"
  - name: "元大南屯"
  - name: "台新建北"
  - name: "元富松德"